import json
import sys

sys.stdout.reconfigure(encoding='utf-8')

# The 20 Ranked Coffees Dataset (100g Packages)
# Top 10 Active Picks + 10 Overlapping/Duplicate Picks (Grayed out)

TOP_20_DATA = [
    # 1. Active Pick 1
    {
        'rank': 1,
        'is_active': True,
        'roastery': 'Archers Coffee',
        'roastery_badge': '🏹 Archers',
        'title': 'Panama - Finca Auromar, Geisha Washed Peaberry',
        'handle': 'panama-finca-auromar-malla-geisha-washed-peaberry',
        'source_url': 'https://archerscoffee.com/products/panama-finca-auromar-malla-geisha-washed-peaberry',
        'country': 'Panama',
        'farm': 'Finca Auromar (Roberto Brenes)',
        'variety': 'Geisha (Peaberry)',
        'process': 'Washed',
        'altitude': '1,770 masl',
        'roast': 'Filter / Light Roast',
        'notes': 'Jasmine, White Tea, Bergamot, Champagne Acidity',
        'weight': '100g',
        'price_aed': 98.0,
        'price_krw': 37240,
        'score_taste': 40,
        'score_value': 28,
        'score_rarity': 30,
        'score_total': 98,
        'review_comment': 'BOP 챔피언 오로마르 농장의 전체 수확량 3~5% 미만 희귀 피베리(Peaberry) 독점 랏. 국내 일반 플랫빈(8~10만원) 대비 정확히 50% 반값 수준. 백호은침 백차와 샴페인의 영롱한 티라이크 정점.',
        'overlap_note': '선발 (파나마 게이샤 피베리 워시드 최고봉)'
    },
    # 2. Active Pick 2
    {
        'rank': 2,
        'is_active': True,
        'roastery': 'Archers Coffee',
        'roastery_badge': '🏹 Archers',
        'title': 'Ethiopia - Elto Coffee Sama Washed',
        'handle': 'ethiopia-elto-coffee-sama-washed',
        'source_url': 'https://archerscoffee.com/products/ethiopia-elto-coffee-sama-washed',
        'country': 'Ethiopia',
        'farm': 'Sama Village (Elto Coffee)',
        'variety': '74158 (Single Variety)',
        'process': 'Washed',
        'altitude': '2,350 masl',
        'roast': 'Filter / Light Roast',
        'notes': 'Peach Iced Tea, Jasmine, Lemongrass, Floral Honey',
        'weight': '100g',
        'price_aed': 28.0,
        'price_krw': 10640,
        'score_taste': 38,
        'score_value': 30,
        'score_rarity': 29,
        'score_total': 97,
        'review_comment': '해발 2,350m 초고고도 단일 품종(74158) 정통 워시드. 100g 10,640원이라는 경이로운 가성비로 복숭아 아이스티와 자스민, 레몬그라스의 맑은 티 텍스처를 뿜어내는 데일리 종결 원두.',
        'overlap_note': '선발 (에티오피아 2,350m 단일품종 워시드 극가성비)'
    },
    # 3. Active Pick 3
    {
        'rank': 3,
        'is_active': True,
        'roastery': 'Archers Coffee',
        'roastery_badge': '🏹 Archers',
        'title': 'Ethiopia - Hamasho Village Washed Archers Lot 2025',
        'handle': 'ethiopia-hamasho-village-washed-archers-lot-2025',
        'source_url': 'https://archerscoffee.com/products/ethiopia-hamasho-village-washed-archers-lot-2025',
        'country': 'Ethiopia',
        'farm': 'Hamasho Village (Daye Bensa / Asefa Dukamo)',
        'variety': '74158',
        'process': 'Washed',
        'altitude': '2,300 masl',
        'roast': 'Filter / Light Roast',
        'notes': 'Bergamot, Orange Blossom, Earl Grey, Citrus Clean Cup',
        'weight': '100g',
        'price_aed': 33.0,
        'price_krw': 12540,
        'score_taste': 39,
        'score_value': 29,
        'score_rarity': 28,
        'score_total': 96,
        'review_comment': '에티오피아 COE 2위 명문 다예 벤사(Daye Bensa)의 아처스 독점 하마쇼 워시드 랏. 국내 유사 랏(2.5~3만원) 대비 반값 이하이며 얼그레이 홍차와 오렌지 블라썸의 우아한 클린컵.',
        'overlap_note': '선발 (에티오피아 시다마 벤사 2,300m COE 명문 워시드)'
    },
    # 4. Active Pick 4
    {
        'rank': 4,
        'is_active': True,
        'roastery': 'The Espresso Lab',
        'roastery_badge': '☕ The Espresso Lab',
        'title': 'SL28 Santa Isabel',
        'handle': 'sl28-santa-isabel-3',
        'source_url': 'https://theespressolab.com/products-details/sl28-santa-isabel-3',
        'country': 'Panama',
        'farm': 'Finca Santa Isabel',
        'variety': 'SL28',
        'process': 'Washed',
        'altitude': '1,500 masl',
        'roast': 'Filter (Light Roast)',
        'notes': 'Jasmine, Grapefruit, Redcurrant, Rooibos Tea',
        'weight': '100g',
        'price_aed': 75.5,
        'price_krw': 28690,
        'score_taste': 38,
        'score_value': 28,
        'score_rarity': 29,
        'score_total': 95,
        'review_comment': '파나마 보케테 화산 테루아에서 재배된 극희귀 SL28 워시드 랏. 케냐 품종 특유의 보석 같은 구연산 산미와 파나마의 화사한 꽃향이 결합. 2.8만원대 파나마 극가성비 국내 미수입 랏.',
        'overlap_note': '선발 (파나마 보케테 희귀 SL28 품종 워시드)'
    },
    # 5. Active Pick 5
    {
        'rank': 5,
        'is_active': True,
        'roastery': 'Archers Coffee',
        'roastery_badge': '🏹 Archers',
        'title': 'Panama - Elida Geisha Plano 2801 Washed',
        'handle': 'panama-elida-estate-geisha-plano-2801',
        'source_url': 'https://archerscoffee.com/products/panama-elida-estate-geisha-plano-2801',
        'country': 'Panama',
        'farm': 'Elida Estate (Wilford Lamastus Family)',
        'variety': 'Geisha (Plano)',
        'process': 'Washed',
        'altitude': '1,950 masl',
        'roast': 'Filter / Light Roast',
        'notes': 'Lavender, Bergamot, White Tea, Honeycomb',
        'weight': '100g',
        'price_aed': 143.0,
        'price_krw': 54340,
        'score_taste': 40,
        'score_value': 24,
        'score_rarity': 30,
        'score_total': 94,
        'review_comment': '세계 최고가 옥션 명문 엘리다 에스테이트(파운드당 $4,541 신기록)의 Plano 2801 워시드 나노랏. 자극적인 발효취가 전무하며 라벤더와 백차의 극도로 우아한 질감. 국내 시세 대비 35% 할인.',
        'overlap_note': '선발 (파나마 보케테 엘리다 옥션 명문 화이트티 워시드)'
    },
    # 6. Active Pick 6
    {
        'rank': 6,
        'is_active': True,
        'roastery': 'The Espresso Lab',
        'roastery_badge': '☕ The Espresso Lab',
        'title': 'El Rubi Parainema Anaerobic Washed Lot A',
        'handle': 'el-rubi-parainema-anaerobic-washed-lot-a',
        'source_url': 'https://theespressolab.com/products-details/el-rubi-parainema-anaerobic-washed-lot-a',
        'country': 'Colombia',
        'farm': 'Finca El Rubi (Heber Sarria)',
        'variety': 'Parainema',
        'process': 'Anaerobic Washed',
        'altitude': '1,700 masl',
        'roast': 'Filter (Light Roast)',
        'notes': 'White Tea, Lychee, Lemon Verbena, Sweet Green Grape',
        'weight': '100g',
        'price_aed': 60.0,
        'price_krw': 22800,
        'score_taste': 37,
        'score_value': 28,
        'score_rarity': 28,
        'score_total': 93,
        'review_comment': '온두라스에서 기원한 희귀 품종 파라이네마의 섬세한 화이트 티(White Tea) & 리치 뉘앙스를 콜롬비아 우일라에서 무산소 워시드로 구현. 100g 22,800원의 놀라운 가성비.',
        'overlap_note': '선발 (콜롬비아 희귀 품종 파라이네마 화이트티 텍스처)'
    },
    # 7. Active Pick 7
    {
        'rank': 7,
        'is_active': True,
        'roastery': 'Archers Coffee',
        'roastery_badge': '🏹 Archers',
        'title': 'Ecuador - Fincas Del Putushio, Typica Mejorado',
        'handle': 'finca-del-putushio-typica-mejorado-rt',
        'source_url': 'https://archerscoffee.com/products/finca-del-putushio-typica-mejorado-rt',
        'country': 'Ecuador',
        'farm': 'Finca Del Putushio (Vinicio Martinez)',
        'variety': 'Typica Mejorado',
        'process': 'Classic Washed',
        'altitude': '2,100 masl',
        'roast': 'Filter / Light Roast',
        'notes': 'Jasmine Blossom, Sweet Lime, Herbal Tea, Crisp Apple',
        'weight': '100g',
        'price_aed': 83.0,
        'price_krw': 31540,
        'score_taste': 38,
        'score_value': 26,
        'score_rarity': 28,
        'score_total': 92,
        'review_comment': '에콰도르 로하 2,100m 최고봉 테루아의 희귀 품종 티피카 메호라도. 게이샤를 뛰어넘는 자스민과 스위트 라임 허브티 톤을 선사하며, 국내 시세(6만원대) 대비 50% 저렴.',
        'overlap_note': '선발 (에콰도르 최고봉 메호라도 자스민/라임 허브티)'
    },
    # 8. Active Pick 8
    {
        'rank': 8,
        'is_active': True,
        'roastery': 'Archers Coffee',
        'roastery_badge': '🏹 Archers',
        'title': 'Panama - Finca Los Cenizos Geisha Washed GW-208',
        'handle': 'panama-finca-los-cenizos-geisha-washed-gw-208',
        'source_url': 'https://archerscoffee.com/products/panama-finca-los-cenizos-geisha-washed-gw-208',
        'country': 'Panama',
        'farm': 'Finca Los Cenizos (Jose Gallardo)',
        'variety': 'Geisha',
        'process': 'Washed',
        'altitude': '2,050 masl',
        'roast': 'Filter / Light Roast',
        'notes': 'White Peach Iced Tea, Earl Grey, Bergamot, Sparkling Floral',
        'weight': '100g',
        'price_aed': 210.0,
        'price_krw': 79800,
        'score_taste': 40,
        'score_value': 22,
        'score_rarity': 30,
        'score_total': 92,
        'review_comment': '바루 화산 최고봉 해발 2,050m에 위치한 로스 세니소스의 극상 나노랏. 국내 수입 이력 전무 100% 독점 랏. 복숭아 아이스티와 얼그레이 홍차 뉘앙스가 선명하게 응축된 하이엔드.',
        'overlap_note': '선발 (파나마 2,050m 바루 화산 최고봉 복숭아 아이스티 워시드)'
    },
    # 9. Active Pick 9
    {
        'rank': 9,
        'is_active': True,
        'roastery': 'The Espresso Lab',
        'roastery_badge': '☕ The Espresso Lab',
        'title': 'Kotowa Las Brujas Ethiopian Natural Lot 4219',
        'handle': 'kotowa-las-brujas-ethiopian-natural-lot-4219',
        'source_url': 'https://theespressolab.com/products-details/kotowa-las-brujas-ethiopian-natural-lot-4219',
        'country': 'Panama',
        'farm': 'Finca Kotowa Las Brujas (Alexander McIntosh)',
        'variety': 'Ethiopian Heirloom',
        'process': 'Natural',
        'altitude': '1,700 masl',
        'roast': 'Filter (Light Roast)',
        'notes': 'Chamomile, Dried Apricot, Honey, Orange Tea',
        'weight': '100g',
        'price_aed': 60.0,
        'price_krw': 22800,
        'score_taste': 36,
        'score_value': 28,
        'score_rarity': 28,
        'score_total': 92,
        'review_comment': '100년 역사의 파나마 코토와 농장에서 에티오피아 토착종을 화산 토양에 이식한 이색 나노랏. 과발효 없이 카모마일 꽃차와 살구의 투명하고 우아한 허브티 톤. 100g 22,800원 극가성비.',
        'overlap_note': '선발 (파나마 화산 에티오피아 토착종 카모마일 허브티)'
    },
    # 10. Active Pick 10
    {
        'rank': 10,
        'is_active': True,
        'roastery': 'Archers Coffee',
        'roastery_badge': '🏹 Archers',
        'title': 'Colombia - Cota Coffee Finca Rio Negro Pink Bourbon - Zest life',
        'handle': 'colombia-cota-coffee-finca-rio-negro-pink-bourbon-zest-life',
        'source_url': 'https://archerscoffee.com/products/colombia-cota-coffee-finca-rio-negro-pink-bourbon-zest-life',
        'country': 'Colombia',
        'farm': 'Finca Rio Negro (Cota Coffee)',
        'variety': 'Pink Bourbon',
        'process': 'Washed - Co-ferment',
        'altitude': '1,800 masl',
        'roast': 'Filter / Light Roast',
        'notes': 'Pink Grapefruit, Mandarin Zest, Hibiscus Tea, Floral Honey',
        'weight': '100g',
        'price_aed': 53.0,
        'price_krw': 20140,
        'score_taste': 36,
        'score_value': 27,
        'score_rarity': 28,
        'score_total': 91,
        'review_comment': '콜롬비아 명품 핑크버번 품종을 감귤 제스트와 함께 정밀 공발효 워시드 가공. 자몽과 히비스커스 티의 밝고 청량한 산미를 뿜어내는 2만원대 매력적인 티라이크 원두.',
        'overlap_note': '선발 (콜롬비아 핑크버번 워시드 산뜻한 시트러스티)'
    },

    # --- BELOW: Ranked 11~20 (Duplicate/Overlapping Taste - Grayed Out) ---
    # 11. Overlap 1 (Auromar Farm Duplicate)
    {
        'rank': 11,
        'is_active': False,
        'roastery': 'The Espresso Lab',
        'roastery_badge': '☕ The Espresso Lab',
        'title': 'Auromar Firestone',
        'handle': 'auromar-firestone-7',
        'source_url': 'https://theespressolab.com/products-details/auromar-firestone-7',
        'country': 'Panama',
        'farm': 'Finca Auromar (Roberto Brenes)',
        'variety': 'Geisha',
        'process': 'Washed Anaerobic',
        'altitude': '1,770 masl',
        'roast': 'Filter (Light Roast)',
        'notes': 'Jasmine, White Tea, Bergamot, Sparkling Grape',
        'weight': '100g',
        'price_aed': 175.0,
        'price_krw': 66500,
        'score_taste': 40,
        'score_value': 20,
        'score_rarity': 29,
        'score_total': 89,
        'review_comment': '2022 BOP 1위 챔피언 Firestone 랏. 훌륭한 백차/자스민 티라이크이지만, #1위 [Auromar Geisha Peaberry]와 농장 및 티라이크 풍미가 일치하며 가격(175 AED vs 98 AED) 대비 1위 피베리가 가성비 우위.',
        'overlap_note': '🚫 #1위 [Auromar Peaberry Washed]와 동일 농장 & 자스민/백차 티라이크 프로필 중복'
    },
    # 12. Overlap 2 (Elto Sama Producer Duplicate)
    {
        'rank': 12,
        'is_active': False,
        'roastery': 'Archers Coffee',
        'roastery_badge': '🏹 Archers',
        'title': 'Ethiopia - Elto Coffee Elora Station Classic Washed',
        'handle': 'ethiopia-elto-coffee-elora-station-classic-washed',
        'source_url': 'https://archerscoffee.com/products/ethiopia-elto-coffee-elora-station-classic-washed',
        'country': 'Ethiopia',
        'farm': 'Elora Station (Elto Coffee)',
        'variety': '74158',
        'process': 'Classic Washed',
        'altitude': '2,400 masl',
        'roast': 'Filter / Light Roast',
        'notes': 'Ginger Ale, Jasmine, White Peach, Lemongrass',
        'weight': '100g',
        'price_aed': 33.0,
        'price_krw': 12540,
        'score_taste': 36,
        'score_value': 28,
        'score_rarity': 25,
        'score_total': 89,
        'review_comment': '2,400m 초고고도 워시드로 훌륭하나, #2위 [Elto Sama Washed]와 동일 생산자(Elto) 및 74158 품종 복숭아/자스민 톤이 직접 중복되어 2위 사마 랏으로 단일화.',
        'overlap_note': '🚫 #2위 [Elto Coffee Sama Washed]와 동일 생산자 & 74158 워시드 복숭아/자스민 중복'
    },
    # 13. Overlap 3 (Daye Bensa Hamasho Duplicate)
    {
        'rank': 13,
        'is_active': False,
        'roastery': 'Archers Coffee',
        'roastery_badge': '🏹 Archers',
        'title': 'Ethiopia - Daye Bensa Rumudamo DFW Archers Lot',
        'handle': 'ethiopia-daye-bensa-rumudamo-dfw-archers-lot',
        'source_url': 'https://archerscoffee.com/products/ethiopia-daye-bensa-rumudamo-dfw-archers-lot',
        'country': 'Ethiopia',
        'farm': 'Rumudamo (Daye Bensa)',
        'variety': '74158',
        'process': 'Dry Ferment Washed',
        'altitude': '2,200 masl',
        'roast': 'Filter / Light Roast',
        'notes': 'Earl Grey, Lavender, Apricot, Lemon Peel',
        'weight': '100g',
        'price_aed': 52.0,
        'price_krw': 19760,
        'score_taste': 36,
        'score_value': 26,
        'score_rarity': 26,
        'score_total': 88,
        'review_comment': '다예 벤사의 루무다모 건식발효 워시드. #3위 [Hamasho Village Washed]와 동일 다예 벤사 74158 워시드 얼그레이 계열 노트가 겹치며 하마쇼 랏이 가격(33 AED)에서 더 우수.',
        'overlap_note': '🚫 #3위 [Hamasho Village Washed]와 동일 다예 벤사 74158 얼그레이 계열 중복'
    },
    # 14. Overlap 4 (Panama Geisha Boquete Washed Overlap)
    {
        'rank': 14,
        'is_active': False,
        'roastery': 'Archers Coffee',
        'roastery_badge': '🏹 Archers',
        'title': 'Panama - Adaura Coffee Geisha Washed Jer DRD',
        'handle': 'panama-adaura-coffee-geisha-washed-jer-drd',
        'source_url': 'https://archerscoffee.com/products/panama-adaura-coffee-geisha-washed-jer-drd',
        'country': 'Panama',
        'farm': 'Adaura Coffee (Alto Jaramillo)',
        'variety': 'Geisha',
        'process': 'Washed',
        'altitude': '1,750 masl',
        'roast': 'Filter / Light Roast',
        'notes': 'Jasmine, White Tea, Orange Blossom, Honey',
        'weight': '100g',
        'price_aed': 120.0,
        'price_krw': 45600,
        'score_taste': 38,
        'score_value': 22,
        'score_rarity': 27,
        'score_total': 87,
        'review_comment': '알토 하라미요의 아다우라 게이샤 워시드. 우수한 품질이지만 이미 상위에 #5위 [Elida Plano 2801]과 #1위 [Auromar Peaberry]가 선발되어 보케테 게이샤 워시드 프로필 중복.',
        'overlap_note': '🚫 #5위 [Elida Plano] 및 #1위 [Auromar]와 파나마 게이샤 워시드 자스민/백차 중복'
    },
    # 15. Overlap 5 (Panama Geisha Washed Overlap)
    {
        'rank': 15,
        'is_active': False,
        'roastery': 'Archers Coffee',
        'roastery_badge': '🏹 Archers',
        'title': 'Panama - Los Lajones Bambu Geisha Washed Lot 20C',
        'handle': 'panama-los-lajones-bambu-geisha-washed-lot-20c',
        'source_url': 'https://archerscoffee.com/products/panama-los-lajones-bambu-geisha-washed-lot-20c',
        'country': 'Panama',
        'farm': 'Los Lajones (Graciano Cruz)',
        'variety': 'Green Tip Geisha',
        'process': 'Washed',
        'altitude': '1,800 masl',
        'roast': 'Filter / Light Roast',
        'notes': 'White Peach, Jasmine, Bergamot, Lime Blossom',
        'weight': '100g',
        'price_aed': 135.0,
        'price_krw': 51300,
        'score_taste': 38,
        'score_value': 21,
        'score_rarity': 28,
        'score_total': 87,
        'review_comment': '그라시아노 크루즈의 로스 라호네스 밤부 랏. 화사한 복숭아/자스민 워시드이나 #8위 [Los Cenizos] 및 #5위 [Elida]와 파나마 게이샤 워시드 카테고리 겹침.',
        'overlap_note': '🚫 #8위 [Los Cenizos] 및 #5위 [Elida]와 파나마 고고도 게이샤 워시드 중복'
    },
    # 16. Overlap 6 (Panama Chevas Geisha Washed Overlap)
    {
        'rank': 16,
        'is_active': False,
        'roastery': 'Archers Coffee',
        'roastery_badge': '🏹 Archers',
        'title': 'Panama - Chevas Limited El Choclo GW Venus',
        'handle': 'panama-chevas-limited-el-choclo-gw-venus',
        'source_url': 'https://archerscoffee.com/products/panama-chevas-limited-el-choclo-gw-venus',
        'country': 'Panama',
        'farm': 'Chevas Limited (El Choclo)',
        'variety': 'Geisha',
        'process': 'Washed',
        'altitude': '1,650 masl',
        'roast': 'Filter / Light Roast',
        'notes': 'Jasmine, White Tea, Sweet Orange, Floral Nectar',
        'weight': '100g',
        'price_aed': 145.0,
        'price_krw': 55100,
        'score_taste': 38,
        'score_value': 20,
        'score_rarity': 28,
        'score_total': 86,
        'review_comment': '세바스 리미티드의 엘 초클로 게이샤 워시드. 하라미요 테루아의 아름다운 꽃향이지만 상위 파나마 게이샤 워시드 3종과 직접적인 컵노트 중복.',
        'overlap_note': '🚫 #5위 [Elida] 및 #1위 [Auromar]와 파나마 게이샤 워시드 자스민/백차 중복'
    },
    # 17. Overlap 7 (Elto Kokose Producer Overlap)
    {
        'rank': 17,
        'is_active': False,
        'roastery': 'Archers Coffee',
        'roastery_badge': '🏹 Archers',
        'title': 'Ethiopia - Elto Coffee Kokose Natural Lot 2',
        'handle': 'ethiopia-elto-coffee-kokose-natural-lot-2',
        'source_url': 'https://archerscoffee.com/products/ethiopia-elto-coffee-kokose-natural-lot-2',
        'country': 'Ethiopia',
        'farm': 'Kokose Village (Elto Coffee)',
        'variety': '74158',
        'process': 'Classic Natural',
        'altitude': '2,300 masl',
        'roast': 'Filter / Light Roast',
        'notes': 'Strawberry, Ripe Peach, Jasmine, Honey',
        'weight': '100g',
        'price_aed': 33.0,
        'price_krw': 12540,
        'score_taste': 34,
        'score_value': 27,
        'score_rarity': 25,
        'score_total': 86,
        'review_comment': '엘토 커피의 코코세 내추럴. 달콤한 베리/복숭아이지만 사용자 선호인 워시드 티라이크에 비해 내추럴 성향이며 #2위 [Elto Sama Washed]와 동일 생산자 중복.',
        'overlap_note': '🚫 #2위 [Elto Sama Washed] 생산자 중복 & 워시드 티라이크 선호 기준 후순위'
    },
    # 18. Overlap 8 (Hamasho Station Duplicate)
    {
        'rank': 18,
        'is_active': False,
        'roastery': 'Archers Coffee',
        'roastery_badge': '🏹 Archers',
        'title': 'Ethiopia - Hamasho Village Asefa Dukamo Station Honey Archers Lot',
        'handle': 'ethiopia-hamasho-village-asefa-dukamo-station-honey-archers-lot',
        'source_url': 'https://archerscoffee.com/products/ethiopia-hamasho-village-asefa-dukamo-station-honey-archers-lot',
        'country': 'Ethiopia',
        'farm': 'Hamasho Village (Daye Bensa)',
        'variety': '74158',
        'process': 'Honey',
        'altitude': '2,300 masl',
        'roast': 'Filter / Light Roast',
        'notes': 'Peach, Orange Blossom, Honey, Black Tea',
        'weight': '100g',
        'price_aed': 33.0,
        'price_krw': 12540,
        'score_taste': 35,
        'score_value': 26,
        'score_rarity': 25,
        'score_total': 86,
        'review_comment': '하마쇼 마을의 허니 프로세스. 달콤하고 화사하지만 #3위 [Hamasho Washed]와 동일 농장/스테이션 랏으로 단일화 추천.',
        'overlap_note': '🚫 #3위 [Hamasho Washed]와 동일 농장/스테이션 및 원산지 중복'
    },
    # 19. Overlap 9 (Colombia CGLE Duplicate)
    {
        'rank': 19,
        'is_active': False,
        'roastery': 'The Espresso Lab',
        'roastery_badge': '☕ The Espresso Lab',
        'title': 'CGLE La Margritas Geisha Honey',
        'handle': 'cgle-la-margritas-geisha-honey',
        'source_url': 'https://theespressolab.com/products-details/cgle-la-margritas-geisha-honey',
        'country': 'Colombia',
        'farm': 'Finca Las Margaritas (CGLE)',
        'variety': 'Geisha',
        'process': 'Honey',
        'altitude': '1,800 masl',
        'roast': 'Filter (Light Roast)',
        'notes': 'Orange Blossom, Jasmine, Tropical Nectar, Honey',
        'weight': '100g',
        'price_aed': 145.01,
        'price_krw': 55100,
        'score_taste': 37,
        'score_value': 22,
        'score_rarity': 26,
        'score_total': 85,
        'review_comment': '콜롬비아 CGLE의 마르가리타스 게이샤 허니. 훌륭한 오렌지 블라썸이지만 이미 #6위 [El Rubi Parainema] 및 #10위 [Cota Pink Bourbon]이 선발되었고 145 AED 가격대 대비 파나마 게이샤와 경쟁 열세.',
        'overlap_note': '🚫 콜롬비아 스페셜티 랏 중복 & 파나마 게이샤 옥션 랏 대비 가성비 경합'
    },
    # 20. Overlap 10 (Panama Mil Cumbres Washed Overlap)
    {
        'rank': 20,
        'is_active': False,
        'roastery': 'Archers Coffee',
        'roastery_badge': '🏹 Archers',
        'title': 'Panama - Mil Cumbres GIL GW lot 2',
        'handle': 'panama-mil-cumbres-gil-gw-lot-2',
        'source_url': 'https://archerscoffee.com/products/panama-mil-cumbres-gil-gw-lot-2',
        'country': 'Panama',
        'farm': 'Mil Cumbres',
        'variety': 'Geisha',
        'process': 'Washed',
        'altitude': '1,800 masl',
        'roast': 'Filter / Light Roast',
        'notes': 'Jasmine, White Tea, Crisp Green Apple, Bergamot',
        'weight': '100g',
        'price_aed': 143.0,
        'price_krw': 54340,
        'score_taste': 38,
        'score_value': 20,
        'score_rarity': 26,
        'score_total': 84,
        'review_comment': '밀 쿰브레스의 게이샤 워시드 랏. 전형적인 자스민과 백차 톤을 지녔으나 이미 #5위 [Elida Plano] 및 #1위 [Auromar Peaberry]와 완전히 동일한 파나마 게이샤 워시드 향미 구조.',
        'overlap_note': '🚫 #5위 [Elida] 및 #1위 [Auromar]와 파나마 게이샤 워시드 백차/자스민 톤 중복'
    }
]

with open('top_20_curation.json', 'w', encoding='utf-8') as f:
    json.dump(TOP_20_DATA, f, ensure_ascii=False, indent=2)

print("Saved top_20_curation.json successfully with 10 Active + 10 Overlapping Coffees!")
